# Generated by Django 6.0.4 on 2026-05-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Bag', 'Bag'), ('ID Card', 'ID Card'), ('Keys', 'Keys'), ('Other', 'Other')], max_length=100)),
                ('image', models.ImageField(upload_to='items/')),
                ('date_lost', models.DateField()),
                ('owner_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_contact', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Both', 'Both')], max_length=100)),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='Lost', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
