# Generated by Django 6.0.4 on 2026-05-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_options_item_updated_at_item_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='preferred_contact',
        ),
    ]
